{{- if and (.Values.krakend) (.Values.krakend.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.destinationServer}}-krakend
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    pod-security.kubernetes.io/enforce: privileged
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: clusters/core/addons/krakend
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: krakend
  destination:
    name: {{ .Values.destinationServer | default "in-cluster" }}
    namespace: krakend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace={{ .Values.krakend.createNamespace }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
