{{- if and (index .Values "minio-operator") (index .Values "minio-operator" "enable") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.destinationServer}}-minio-operator
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    pod-security.kubernetes.io/enforce: privileged
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: clusters/core/addons/minio-operator
    targetRevision: {{ .Values.targetRevision }}
  destination:
    name: {{ .Values.destinationServer | default "in-cluster" }}
    namespace: minio-operator
    helm:
      releaseName: minio-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace={{ (index .Values "minio-operator" "createNamespace") }}
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  namespace:
    metadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
        pod-security.kubernetes.io/enforce: privileged
{{- end -}}
