# we use Harbor secret to consolidate all the Harbor secrets
existingSecretAdminPassword: harbor
existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
existingSecretSecretKey: harbor

core:
  # The XSRF key. Will be generated automatically if it isn't specified
  xsrfKey: ""
jobservice:
  # Secret is used when job service communicates with other components.
  # If a secret key is not specified, Helm will generate one.
  # Must be a string of 16 chars.
  secret: ""
registry:
  # Secret is used to secure the upload state from client
  # and registry storage backend.
  # If a secret key is not specified, Helm will generate one.
  # Must be a string of 16 chars.
  secret: ""
  credentials:
    username: harbor_registry_user
    existingSecret: harbor
fullnameOverride: harbor
# If Harbor is deployed behind the proxy, set it as the URL of proxy
externalURL: https://harbor.techsecoms.com
ipFamily:
  ipv6:
    enabled: false
expose:
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.techsecoms.com
      notary: notary.techsecoms.com
updateStrategy:
  type: Recreate
persistence:
  persistentVolumeClaim:
    registry:
      size: 30Gi
    jobservice:
      jobLog:
        size: 1Gi
    database:
      size: 2Gi
    redis:
      size: 1Gi
    trivy:
      size: 5Gi
database:
  internal:
    # The initial superuser password for internal database
    password: "CanIseeu@2012"
