apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: local-secret-store
  namespace: harbor-system
spec:
  provider:
    kubernetes:
      auth:
        serviceAccountRef:
          name: default
      remoteNamespace: harbor-system  # Target namespace for the secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor
  namespace: harbor-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore  # Changed from ClusterSecretStore to SecretStore
    name: local-secret-store  # Updated to match the SecretStore name
  target:
    name: harbor-secrets  # Name of the Kubernetes Secret that will be created
    template:
      type: Opaque
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /control-plane/deploy-secrets
        property: harbor.HARBOR_ADMIN_PASSWORD
    - secretKey: secretKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /control-plane/deploy-secrets
        property: harbor.secretKey
    - secretKey: REGISTRY_HTPASSWD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /control-plane/deploy-secrets
        property: harbor.REGISTRY_HTPASSWD
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /control-plane/deploy-secrets
        property: harbor.REGISTRY_PASSWD
